# Generated by Django 2.2.6 on 2019-10-25 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=20, verbose_name='Enter first name: ')),
                ('Last_name', models.CharField(max_length=20, verbose_name='Enter last name: ')),
                ('Age', models.IntegerField(default=0, verbose_name='Enter your age')),
                ('Phone_number', models.IntegerField(verbose_name='Enter your phone number here')),
            ],
        ),
    ]
