# Generated by Django 2.2.6 on 2019-10-25 11:31

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_mydetails'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='mydetails',
            managers=[
                ('obj', django.db.models.manager.Manager()),
            ],
        ),
    ]
