# Generated by Django 2.2.6 on 2019-10-31 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20191025_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=12)),
                ('Last_name', models.CharField(max_length=12)),
            ],
        ),
    ]
